# Generated by Django 4.2.7 on 2023-11-13 16:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polyconnmain", "0002_rename_native_languages_user_native_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="district",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="polyconnmain.district",
            ),
            preserve_default=False,
        ),
    ]
