# Generated by Django 4.2.7 on 2023-11-13 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polyconnmain", "0005_reservation_district"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="district",
        ),
    ]
