# Generated by Django 4.2.7 on 2023-11-13 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polyconnmain", "0006_remove_reservation_district"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="district",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="polyconnmain.district",
            ),
            preserve_default=False,
        ),
    ]
