# Generated by Django 4.2.7 on 2023-11-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polyconnmain", "0008_remove_reservation_district"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="hobbies",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="learning_languages",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="native_language",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
