# Generated by Django 4.2.7 on 2023-11-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "polyconnmain",
            "0009_alter_user_hobbies_alter_user_learning_languages_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="participants",
        ),
        migrations.AddField(
            model_name="reservation",
            name="participants",
            field=models.ManyToManyField(
                related_name="participating_reservations", to="polyconnmain.user"
            ),
        ),
    ]
