# Generated by Django 4.2.7 on 2023-11-16 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polyconnmain", "0011_remove_event_participants_userevent_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="name",
            new_name="event_name",
        ),
    ]
