# Generated by Django 4.2.7 on 2023-11-17 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("polyconnmain", "0012_rename_name_event_event_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="participants",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="participants",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="user",
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Reservation_Participants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polyconnmain.reservation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polyconnmain.user",
                    ),
                ),
            ],
            options={
                "unique_together": {("reservation", "user")},
            },
        ),
    ]
